tabWidth: 2
useTabs: false
semi: false
singleQuote: true
printWidth: 120
quoteProps: "consistent"
trailingComma: "all"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "always"
endOfLine: "lf"
