#+OPTIONS: ^:nil
#+TITLE: RelayerMS
#+DATE: <2018-12-11 Tue>
#+AUTHOR: Vu Tran
#+EMAIL: me@vutr.io`

* Content                                                               :TOC:
- [[#introduction][Introduction]]
- [[#first][First]]
  - [[#pre-requisite][Pre-requisite]]
  - [[#setup][Setup]]
  - [[#start-hacking][Start hacking]]

* Introduction
A Relayer Manager, spawning custom relayer to tomochain blockchain infrastructure at will

* First
** Pre-requisite
- Python 3.7 (recommended installing with pyenv)
- pipenv
- nvm
- yarn
- Docker

** Setup
- Install required & frontend dependencies
  #+begin_src sh
  $ yarn
  #+end_src
- Install backend dependencies
  #+begin_src sh
  $ pipenv install
  #+end_src
- Fireup database with Docker
  #+begin_src sh
  $ yarn db
  #+end_src
- Start the app
  #+begin_src sh
  $ yarn up
  #+end_src

...or you can start frontend and backend in two separate terminal windows
#+begin_src sh
$ yarn fe
$ yarn be
#+end_src
** Start hacking
backend has the entry point called "app", frontend "index.tsx"
Those are where you get started.

*** Frontend Development
- Libraries for frontend development includes mainly React & BlueprintJS.
- State Management & Code Splitting are handled using native React API instead of external libraries such as Redux and React-Loadable. This keeps the app minimal as
  it could be.
- Stylesheet lang is SASS's SCSS
- Generally, we are using *Typescript Compiler* for compiling ease & speed, also this helps eliminate the redundancy of babel
  plugins. Technically there is nothing change with React Development, except file extension now should be *"tsx"* instead
  of usual *"jsx"*.
- *Wretch* is used instead of Axios/Fetch. It provides smaller and more intuitive async code

*** Backend Development
- Checkout Python Tornado docs...
