version: '2'
services:
  db:
    image: mysql:8
    container_name: relayerms
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.sqldb:/var/lib/mysql
