@baseUrl = http://localhost:8888
@userAddress = 0x070aa7ad03b89b3278f19d34f119dd3c2a244675
@userSignature = 0x534a82e3de6fda201c54126be6892f035918fb6266637063a94c169411cfbf13283e95eb26587ace6d97a09430deff6cf96e6a39a880b4cfc63cabf3a9a0126c1b

###  Getting authenticated
# @name authentication
GET {{baseUrl}}/api/auth?address={{userAddress}}&signature={{userSignature}} HTTP/1.1

### Register a relayer
# @name registration
@token =  {{authentication.response.body.payload.token}}
@coinbase = 0x7BfF9cABAD18efFeC42788EFc473Dd39C90116Aa
@relayerLink = https://dex.devnet.tomochain.com

POST {{baseUrl}}/api/relayer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alpha-Relayer",
  "owner": "{{userAddress}}",
  "coinbase": "{{coinbase}}",
  "deposit": 25000,
  "trade_fee": 1,
  "from_tokens": [],
  "to_tokens": [],
  "link": "{{relayerLink}}",
  "logo": ""
}
